version: '3.8'

services:
  user-service:
    build: ./user-service
    container_name: user-service
    ports:
      - "8001:8000"
    volumes:
      - ./user-service:/var/www
    depends_on:
      - user-db
    networks:
      - app-network

  product-service:
    build: ./product-service
    container_name: product-service
    ports:
      - "8002:8000"
    volumes:
      - ./product-service:/var/www
    depends_on:
      - product-db
    networks:
      - app-network

  auth-service:
    build:
      context: ./auth-service
    container_name: auth-service
    ports:
      - "8003:8000"
    volumes:
      - ./auth-service:/var/www
    depends_on:
      - auth-db
    networks:
      - app-network

  user-db:
    image: mysql:8.0
    container_name: user-db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: user_service
      MYSQL_ROOT_PASSWORD: root
      MYSQL_ALLOW_EMPTY_PASSWORD: "no"

    ports:
      - "3310:3306"
    # Temporarily remove volume to test if volume causes problem
    # volumes:
    #   - user_db_data:/var/lib/mysql
    networks:
      - app-network
  product-db:
    image: mysql:8
    container_name: product-db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: product_service
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3308:3306"
    volumes:
      - product_db_data:/var/lib/mysql
    networks:
      - app-network

  auth-db:
    image: mysql:8
    container_name: auth-db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: auth_service
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3311:3306"
    volumes:
      - auth_db_data:/var/lib/mysql
    networks:
      - app-network

  nginx:
    image: nginx:alpine
    container_name: nginx-gateway
    ports:
      - "80:80"
    volumes:
      - ./api-gateway/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - user-service
      - product-service
      - auth-service
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  user_db_data:
  product_db_data:
  auth_db_data:
